# Generated by Django 4.1.13 on 2025-03-16 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('objet', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('etudiant', 'Étudiant')], max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='auteur',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='telephone',
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='fichier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='filiere',
            field=models.CharField(choices=[('IG', 'Informatique de Gestion'), ('ELM', 'Électronique'), ('AD', 'Administration')], default='IG', max_length=50),
        ),
        migrations.AddField(
            model_name='inscription',
            name='niveau',
            field=models.CharField(choices=[('AP', 'Année Préparatoire'), ('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], default='L1', max_length=50),
        ),
        migrations.AddField(
            model_name='inscription',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='statut_inscription',
            field=models.CharField(choices=[('en attente', 'En attente'), ('validée', 'Validée'), ('rejetée', 'Rejetée')], default='en attente', max_length=50),
        ),
        migrations.AddField(
            model_name='inscription',
            name='type_document',
            field=models.CharField(default='inconnu', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='adresse',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('methode', models.CharField(choices=[('espèces', 'Espèces'), ('mobile money', 'Mobile Money'), ('virement', 'Virement')], max_length=50)),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('effectué', 'Effectué')], default='en attente', max_length=50)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.user')),
            ],
        ),
    ]
