# Generated by Django 5.1.7 on 2025-03-16 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0002_contact_faq_user_remove_inscription_auteur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='filiere',
            field=models.CharField(choices=[('IG', 'Informatique de Gestion'), ('ELM', 'Électro-mecanique'), ('AD', 'Administration')], default='IG', max_length=50),
        ),
    ]
