# Generated by Django 4.1.13 on 2025-04-09 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_alter_contact_nom_alter_contact_objet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(max_length=255),
        ),
    ]
