# Generated by Django 4.1.13 on 2025-04-12 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0006_alter_user_role_customuser'),
    ]

    operations = [
    ]
